################################################################################
#                              SOL LIBRARY v1.0.0+41
#
# File: sol/.travis.yml
#
# Description:
# 	This YAML file is part of the Sol Library. It defines the Travis-CI
# 	build matrix.
#
# Authors:
# 	Abhishek Chakravarti <abhishek@taranjali.org>
#
# Copyright:
# 	(c) 2019, Abhishek Chakravarti.
# 	<abhishek@taranjali.org>
#
# License:
# 	Released under the GNU General Public License version 3 (GPLv3)
# 	<http://opensource.org/licenses/GPL-3.0>. See the accompanying LICENSE
# 	file for complete licensing details.
#
# 	BY CONTINUING TO USE AND/OR DISTRIBUTE THIS FILE, YOU ACKNOWLEDGE THAT
# 	YOU HAVE UNDERSTOOD THESE LICENSE TERMS AND ACCEPT THEM.
################################################################################




#       Set programming language
language: c




#       Set compilers; we're using only GCC for the time being
compiler:
        - gcc




#       Update GCC and GCov to version 8; this is needed for gcov to work
#       properly; refer to the following site:
#       https://gist.github.com/application2000/73fd6f4bf1be6600a2cf9f56315a2d91
before_install:
        - sudo apt-get update
        - sudo apt-get install build-essential software-properties-common -y
        - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        - sudo apt-get update
        - sudo apt-get install gcc-snapshot -y
        - sudo apt-get update
        - sudo apt-get install gcc-8 -y
        - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 60 --slave /usr/bin/gcov gcov /usr/bin/gcov-8




#       Build target
script:
        - make integration
        - less bld/test.log




#       Generate coverage statistics for CodeCov
after_success:
        - bash <(curl -s https://codecov.io/bash)




################################################################################
#				      EOF
#               Built on hyperion [Tue Jan 29 02:37:24 UTC 2019]
################################################################################

